<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TAVA VAJADZBA</name>
   <tag></tag>
   <elementGuidId>4b0d3fec-4c44-4533-b49b-221b450be7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/aside[2]/div[3]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f3c3d93-c9e6-4471-984d-f01ec811ddaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TAVA VAJADZĪBA</value>
      <webElementGuid>0f0e41e4-77a5-4559-b031-893c648be9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR header-fixed-3Fr&quot;]/aside[@class=&quot;navigation-root-23J navigation-root_open-39K&quot;]/div[@class=&quot;categoryMenu-root-Eln&quot;]/div[@class=&quot;categoryMenu-listItem-3os&quot;]/div[@class=&quot;h3-clean categoryMenu-title-3JY&quot;]/span[1]</value>
      <webElementGuid>8f8268ed-809d-4e87-ad06-c89755288d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/aside[2]/div[3]/div[2]/div/span</value>
      <webElementGuid>45863755-6d3d-4ad4-818b-1812fd5cd3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[47]/following::span[1]</value>
      <webElementGuid>115aa460-9331-444a-bc42-a1cac16da69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=','])[47]/following::span[4]</value>
      <webElementGuid>defc37f5-419d-4099-87fd-0b7a7440609e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skatīt visu'])[7]/preceding::span[2]</value>
      <webElementGuid>44248a9f-1d55-421e-8c16-8d4e2c054e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anti-age'])[2]/preceding::span[2]</value>
      <webElementGuid>cc2bdf87-c396-40d5-a57f-f677224f0386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>1d1ce725-d5bb-4a3e-9bd7-c3427ca4e20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TAVA VAJADZĪBA' or . = 'TAVA VAJADZĪBA')]</value>
      <webElementGuid>28645814-409b-4b00-9e8d-0be45354cad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
