<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --WHITE</name>
   <tag></tag>
   <elementGuidId>0196b4af-4a0c-4571-840b-1ed7c110afc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df1c8c7e-cd68-4255-b7ca-122015e00847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>options[11]</value>
      <webElementGuid>7cb3d14d-a35b-457d-8e4b-e98103edba6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_11</value>
      <webElementGuid>6c1dee98-4471-4ff8-96b6-a3bf2323bebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required product-custom-option admin__control-select</value>
      <webElementGuid>be7fa65d-d02a-4c7b-ade5-56e43b066202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selector</name>
      <type>Main</type>
      <value>options[11]</value>
      <webElementGuid>a232b5c2-f5a7-4f68-a9d0-487f892c7fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12be77d1-f567-49e7-b520-802fdf10347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please Select --WHITE</value>
      <webElementGuid>9e7305fe-2966-451d-bcd7-7bca54ccae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_11&quot;)</value>
      <webElementGuid>74d150a5-db78-4478-9ddb-bfa6b6cbea4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_11']</value>
      <webElementGuid>c91b448c-90bc-4017-adfb-dfcb689b192b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div[2]/div/select</value>
      <webElementGuid>5f74497f-3291-4a56-a0d1-793b11576635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTE COLOR'])[1]/following::select[1]</value>
      <webElementGuid>e4401457-3db0-4a76-a2a4-d8b1c775191d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLOVE SIZE'])[1]/following::select[2]</value>
      <webElementGuid>15650e89-f64b-450c-8ead-59df58c38442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[1]</value>
      <webElementGuid>176d51e3-7019-49c0-a867-7af56ce0faee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/preceding::select[1]</value>
      <webElementGuid>09259a54-fd5d-4276-854b-489b636b9460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>4877bf08-1854-41fa-af5e-ccbc63a1bd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'options[11]' and @id = 'select_11' and (text() = '-- Please Select --WHITE' or . = '-- Please Select --WHITE')]</value>
      <webElementGuid>3ba17694-d0f3-4e87-8197-c1cff81bca14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
