<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --SMALLMEDIUMLARGEE_be54f8</name>
   <tag></tag>
   <elementGuidId>d10b20e8-3d24-4b5a-ad53-4c730f6accba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23bfab22-56de-4f21-8319-ced43dd4923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>options[10]</value>
      <webElementGuid>fbaeb811-25d6-444a-a2f6-5b6599d651f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_10</value>
      <webElementGuid>4581d313-fff1-4ce9-91df-c8f389f1dbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> required product-custom-option admin__control-select</value>
      <webElementGuid>4bd6e718-c729-4cdf-a236-86e2f6d5f7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selector</name>
      <type>Main</type>
      <value>options[10]</value>
      <webElementGuid>ea0e7f44-2021-43bb-93bc-97e3f7e5ac55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9263ef29-4052-43af-ad7f-4c08800012e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Please Select --SMALLMEDIUMLARGEEXTRA LARGE</value>
      <webElementGuid>c67c32a1-5092-435b-b69b-76688081e43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_10&quot;)</value>
      <webElementGuid>a9ed5259-3294-47a3-b3f2-9ffb0ddc9285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select_10']</value>
      <webElementGuid>a465adc5-ed82-47ec-ac9d-3fd616e5450c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/select</value>
      <webElementGuid>54b817e3-d2e3-4605-ab3f-aa6b9ed7a673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLOVE SIZE'])[1]/following::select[1]</value>
      <webElementGuid>2297da21-fd29-4025-aabe-324b8e977345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In stock'])[1]/following::select[1]</value>
      <webElementGuid>7d96df67-2530-40d1-a7ae-1440a0f5e70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTE COLOR'])[1]/preceding::select[1]</value>
      <webElementGuid>eeecfa57-18f9-4b0b-943e-a5f91b50302d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[2]</value>
      <webElementGuid>742e7602-92c3-4230-8a00-ea33ab419ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1c280a2d-834c-4f9f-a30f-2b657dc3651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'options[10]' and @id = 'select_10' and (text() = '-- Please Select --SMALLMEDIUMLARGEEXTRA LARGE' or . = '-- Please Select --SMALLMEDIUMLARGEEXTRA LARGE')]</value>
      <webElementGuid>04d56e8b-4ffd-4d54-ae6f-e0092d0f9625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
