<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Piegdes dati_shipping_addressfirstname</name>
   <tag></tag>
   <elementGuidId>32e9070f-187f-44e5-b114-97f51e3260c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3c8e173c-6868-4850-8d71-5a20e8bce2f5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3c8e173c-6868-4850-8d71-5a20e8bce2f5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73b4176d-c719-4bdd-a875-90dbd6823a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>5ec4e415-e69a-4b7c-b27d-5f07b3bc16b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3c8e173c-6868-4850-8d71-5a20e8bce2f5</value>
      <webElementGuid>c4781b62-6a6b-4d7a-b92b-fb39c9042335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[firstname]</value>
      <webElementGuid>add136f0-403a-45f6-a947-1639e1a28c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3c8e173c-6868-4850-8d71-5a20e8bce2f5&quot;)</value>
      <webElementGuid>469de125-0de5-460a-927b-52f7e789ab7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3c8e173c-6868-4850-8d71-5a20e8bce2f5']</value>
      <webElementGuid>bed0943f-1e88-47b5-a84f-f485cacc6e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>a8372521-bffe-463b-9cae-58ab3003ce5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/input</value>
      <webElementGuid>da71914d-3c8d-4b5e-9828-5b7ab5e71bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3c8e173c-6868-4850-8d71-5a20e8bce2f5' and @name = 'shipping_address[firstname]']</value>
      <webElementGuid>5d317138-2509-4399-a191-7d2f78281090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
