<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_dau novads</name>
   <tag></tag>
   <elementGuidId>d2808f41-9e89-4db5-8f1d-e4951352363b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e56fd1e1-30ad-4484-81f5-7d7a0e8b5ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471</value>
      <webElementGuid>fff91e06-e0b5-4022-aae9-6bea5e3a79f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bb6c41bf-bfd7-4f0d-a2ee-8a23c4daf9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d523a4b6-8998-4c78-9c63-b460b9716bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>2f3d4e3d-a07a-40a6-9de9-ea5dd79dfd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ādažu novads</value>
      <webElementGuid>06a47937-3f51-4786-809d-4f65f735f1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471&quot;)</value>
      <webElementGuid>ed0fb2ed-ca2a-40e2-8da9-f6a0e31dba79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471']</value>
      <webElementGuid>3e9767ad-560a-4d1a-b14c-1e9021d64c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_list-box']/li[2]</value>
      <webElementGuid>d2fe9480-1a44-425c-86fd-22c8f8046404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novads'])[2]/following::li[1]</value>
      <webElementGuid>3882ac20-c9c8-468e-8368-1b96f433f79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meklēt'])[2]/following::li[2]</value>
      <webElementGuid>9f8b5bb1-2583-4e65-869f-38fc5f6c477c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aglonas novads'])[2]/preceding::li[1]</value>
      <webElementGuid>76fdcf01-a939-4bc2-9890-c89eed0ddb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aizkraukles novads'])[2]/preceding::li[2]</value>
      <webElementGuid>7051e45e-03f2-4bd1-9349-f42e844b4443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/ul/li[2]</value>
      <webElementGuid>ab0f4b7d-ca83-4941-9d1b-ba672e869e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471' and (text() = 'Ādažu novads' or . = 'Ādažu novads')]</value>
      <webElementGuid>e5f337f4-45b2-4a12-b2e2-4b0bfae09cc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
