<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DPD Kurjers0,49Est. delivery on Oct 05,_bbe9db</name>
   <tag></tag>
   <elementGuidId>d39e2eaa-afb3-48a5-9202-79e829a958e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div[2]/label[3]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>781f5033-def4-48af-bf80-a080057a6388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shippingRadio-description-2AX</value>
      <webElementGuid>921d2a71-3cd6-4327-98b7-20564a5a46bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DPD Kurjers0,49 €Est. delivery on Oct 05, 2022Ilgtspējīgs</value>
      <webElementGuid>ae139b4e-bf86-4e66-a4df-64499b13b1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;main-content-3U-&quot;]/div[@class=&quot;checkoutPage-root-1g1&quot;]/div[@class=&quot;checkoutPage-container-E0x&quot;]/div[@class=&quot;checkoutPage-main-2nO&quot;]/div[1]/div[2]/div[@class=&quot;checkoutStep-root-2-p&quot;]/div[@class=&quot;checkoutStep-content-bW9&quot;]/div[@class=&quot;loaderWrapper-root-PmU&quot;]/form[1]/div[@class=&quot;checkoutFieldset-root-2D6&quot;]/label[@class=&quot;radioGroup-root-2Tl&quot;]/div[@class=&quot;radioGroup-content-22D&quot;]/div[@class=&quot;shippingRadio-root-1nU&quot;]/div[@class=&quot;shippingRadio-description-2AX&quot;]</value>
      <webElementGuid>865895bf-3616-4d64-96b0-ad4b5c04abf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div[2]/label[3]/div[2]/div/div</value>
      <webElementGuid>6e60a65d-7b4e-4fa0-88e1-614415f9cc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Est. delivery on Oct 05, 2022'])[2]/following::div[5]</value>
      <webElementGuid>11152101-f8a7-449d-9506-46917eea8e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bezmaksas'])[2]/following::div[5]</value>
      <webElementGuid>e53e9343-e6d8-4a3a-9db9-d255da8ef33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/div[2]/div/div</value>
      <webElementGuid>d3947425-dfa4-49b8-8220-78330d60f7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DPD Kurjers0,49 €Est. delivery on Oct 05, 2022Ilgtspējīgs' or . = 'DPD Kurjers0,49 €Est. delivery on Oct 05, 2022Ilgtspējīgs')]</value>
      <webElementGuid>a815e42d-817f-4e6c-af1a-ea286b149a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
