<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>2d2e52e5-4afd-4c45-9c89-5a65db70d943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1652c2e6-44d7-4804-a922-77525f18dd6a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1652c2e6-44d7-4804-a922-77525f18dd6a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae7f6c1d-3833-41aa-8eca-6db21d280c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>fb9a2868-a3ca-40a1-a8b6-8977e78fc53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1652c2e6-44d7-4804-a922-77525f18dd6a</value>
      <webElementGuid>5a1c37b5-7277-4ada-afda-6259e82e99f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>547243d6-381a-4adb-86ce-a1d82f3038cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1652c2e6-44d7-4804-a922-77525f18dd6a&quot;)</value>
      <webElementGuid>9fbf8cab-1aa2-4f34-b687-5d576c5e403d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1652c2e6-44d7-4804-a922-77525f18dd6a']</value>
      <webElementGuid>5b464a4e-1f47-4e6c-98c7-ce668358624e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>742bfcb5-374d-4bc3-aa08-708571da78fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7a37b41d-2dc3-4300-97cf-0d120ba4a271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1652c2e6-44d7-4804-a922-77525f18dd6a' and @name = 'shipping_postcode']</value>
      <webElementGuid>58e5e7a5-5051-47f6-9f5a-9294335f0d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
