<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Libya</name>
   <tag></tag>
   <elementGuidId>3117ec98-cf7b-4bc5-aeb5-a971a6c6cf18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfY291bnRyeQ_LY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>173bc374-8cbf-45dc-9e9a-2e6cc57146f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfY291bnRyeQ_LY</value>
      <webElementGuid>f36099b1-c66f-495b-8c54-621d6773967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>588b1d31-b098-4be1-ac3b-1c0da519fa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f0768b3-e9b9-4c85-b9b6-5671770cf7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>e3f0f22f-af15-47e0-91c2-ac69506f1d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libya</value>
      <webElementGuid>6ec808f4-30d4-4f01-962c-9701d2a04342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfY291bnRyeQ_LY&quot;)</value>
      <webElementGuid>31c5eabd-bec0-468a-83dd-05acf79c41c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LY']</value>
      <webElementGuid>eff35fcb-fb43-43cc-97cc-1bd83a20c797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfY291bnRyeQ_list-box']/li[75]</value>
      <webElementGuid>98e7a1d0-681d-464c-9e40-ec20a55e88b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lebanon'])[2]/following::li[1]</value>
      <webElementGuid>79dec4d2-b558-4a24-8755-66cc61a09a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latvia'])[2]/following::li[2]</value>
      <webElementGuid>ae7e463c-25f2-4033-84a5-8c0af814616b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liechtenstein'])[2]/preceding::li[1]</value>
      <webElementGuid>fb4ea256-d2b0-41db-8e7f-d57277fff1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lithuania'])[2]/preceding::li[2]</value>
      <webElementGuid>658d6de7-1215-4814-9e65-174dbabb5494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[75]</value>
      <webElementGuid>328be0dc-8cfb-4fce-8d30-c3a94265f2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfY291bnRyeQ_LY' and (text() = 'Libya' or . = 'Libya')]</value>
      <webElementGuid>0da32a25-118a-466b-8055-e7b6263c8885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
