<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Latvia</name>
   <tag></tag>
   <elementGuidId>947d49c9-9807-4c12-ab9c-f851cdeddf05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfY291bnRyeQ_LV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5ad8bc9a-d50a-42e2-a231-10a39f2659e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfY291bnRyeQ_LV</value>
      <webElementGuid>26fc7ff7-ec78-44b1-94e7-860c99d069c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a7b9c25f-4605-411e-9c37-b8da2b9da58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a446ecf-fbb4-4219-a1fe-4576c1c06948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>c6682910-fe2b-4df0-944b-5e62a7ea954d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latvia</value>
      <webElementGuid>50af3ee4-c862-4028-9cb2-1ee4aabbf716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfY291bnRyeQ_LV&quot;)</value>
      <webElementGuid>be3e541d-4bdb-4247-9a05-cbdb17d343ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LV']</value>
      <webElementGuid>ef212a00-9980-4b83-9a97-eb36c87563e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfY291bnRyeQ_list-box']/li[73]</value>
      <webElementGuid>9d6f73c5-6402-4214-bdf0-fe93ed313245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laos'])[2]/following::li[1]</value>
      <webElementGuid>114f1dec-d7f0-41d7-adfb-2ba8feeb71fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuwait'])[2]/following::li[2]</value>
      <webElementGuid>6c083d4a-e133-4e4c-98bd-6c94141c9a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lebanon'])[2]/preceding::li[1]</value>
      <webElementGuid>30ca5939-3e61-46e5-9905-d34a405b12b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libya'])[2]/preceding::li[2]</value>
      <webElementGuid>70b7a700-97bd-4bc0-8b71-441075c51ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[73]</value>
      <webElementGuid>a0700244-9dfe-4440-8066-3493a8bf017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfY291bnRyeQ_LV' and (text() = 'Latvia' or . = 'Latvia')]</value>
      <webElementGuid>e7583123-490c-43fe-9749-ef2d55688088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
