<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Lebanon</name>
   <tag></tag>
   <elementGuidId>4124b23b-5cc5-4227-a243-d70cd9139f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfY291bnRyeQ_LB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>053b99ed-5fb7-4081-b0d3-f9e0db5e80d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfY291bnRyeQ_LB</value>
      <webElementGuid>579b0489-1743-4b18-99fe-33ea879c8fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3967f2f3-9eb7-4942-a048-07756ea618d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fea0d148-e9b0-4a8b-a9a0-dad61acda0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>51f5131a-422f-474c-aec8-c7b4b2526092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lebanon</value>
      <webElementGuid>f06224b3-e0a1-400e-920e-064e42ef6e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfY291bnRyeQ_LB&quot;)</value>
      <webElementGuid>48f1aa34-a3c1-4ac1-8056-d6f5969132e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfY291bnRyeQ_LB']</value>
      <webElementGuid>32e7cc4f-0360-4ccb-873f-c63d38c54797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfY291bnRyeQ_list-box']/li[74]</value>
      <webElementGuid>57009e5c-5d86-4431-b115-0ba6bcfdf801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latvia'])[2]/following::li[1]</value>
      <webElementGuid>30308ae9-3dea-4032-9251-bc7fd176e948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laos'])[2]/following::li[2]</value>
      <webElementGuid>37fd9c2a-06c2-4cf7-87d8-4280ecd83b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libya'])[2]/preceding::li[1]</value>
      <webElementGuid>03424c70-cab1-459e-af46-ed057c9fc2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liechtenstein'])[2]/preceding::li[2]</value>
      <webElementGuid>7fe77336-8378-4507-b0ba-d92a30eef441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[74]</value>
      <webElementGuid>7714b374-9d0c-4b43-9431-4e989a28da78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfY291bnRyeQ_LB' and (text() = 'Lebanon' or . = 'Lebanon')]</value>
      <webElementGuid>a07197ff-d2d7-498f-8b2e-1292fb114719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
