<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>ec615577-478c-4284-aaa1-0bb0c299eaae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4a3a0081-bef8-4b86-9a43-d4e3585f6dc0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4a3a0081-bef8-4b86-9a43-d4e3585f6dc0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93193389-6967-4239-ae1c-6c1a0b03b883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>f19e2291-a743-43aa-b692-81d4782cdad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4a3a0081-bef8-4b86-9a43-d4e3585f6dc0</value>
      <webElementGuid>e6a6b27e-b3ef-448a-806c-32abb9eba4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>658eec5a-473e-4336-b549-d8fb5eda95d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4a3a0081-bef8-4b86-9a43-d4e3585f6dc0&quot;)</value>
      <webElementGuid>c096e160-e4b0-4243-a729-1b0f61330bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4a3a0081-bef8-4b86-9a43-d4e3585f6dc0']</value>
      <webElementGuid>d354e026-b1fc-44c3-8e96-844b72d5c727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>a4cb0626-a978-4764-abd7-1fa280673cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2950386f-afa5-4f57-bbc7-9fad98d636b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '4a3a0081-bef8-4b86-9a43-d4e3585f6dc0' and @name = 'shipping_postcode']</value>
      <webElementGuid>9d06fbf7-7775-4e38-8a12-7a9c65c741cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
