<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Piegdes dati_shipping_addressfirstname</name>
   <tag></tag>
   <elementGuidId>ec5fc1a2-fc7a-4317-9ab1-284feb9002a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a2d4a1dd-6e9e-4cdc-a592-9ae0b693f74d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ab555ac-30d9-4c36-9665-fd7f2dfeee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>401ff30f-5544-47c2-93fa-8099c8361ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a2d4a1dd-6e9e-4cdc-a592-9ae0b693f74d</value>
      <webElementGuid>76f11c04-34a3-47e7-bb29-f02ed4b9ab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[firstname]</value>
      <webElementGuid>3e5bc921-1280-4eaa-95a2-93e5358bad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2d4a1dd-6e9e-4cdc-a592-9ae0b693f74d&quot;)</value>
      <webElementGuid>591e2d22-8af2-46d8-8296-38599553e490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a2d4a1dd-6e9e-4cdc-a592-9ae0b693f74d']</value>
      <webElementGuid>4144a77d-44ce-4d2a-ab0b-700874550196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>6769b6ea-5cc2-4588-aa04-affbb82220d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/input</value>
      <webElementGuid>8145bea8-2905-4641-a4ff-802bf86bdf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a2d4a1dd-6e9e-4cdc-a592-9ae0b693f74d' and @name = 'shipping_address[firstname]']</value>
      <webElementGuid>b73e19c8-f4a4-4b5b-9bb9-8ce3d87c6341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
