<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>ccfe30d7-2da0-4e76-9b9d-b96f97e2c2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5fabdb9d-3d67-4e62-898f-463cd27b85df</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82846129-f661-4c57-b095-8fe7fafe983e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>ecf2a5e2-7fef-4b4b-96b0-944638010b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5fabdb9d-3d67-4e62-898f-463cd27b85df</value>
      <webElementGuid>f546b211-dbab-40ad-a39f-8854a338a524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>b5d57707-414c-4b18-92db-e7400d64681a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5fabdb9d-3d67-4e62-898f-463cd27b85df&quot;)</value>
      <webElementGuid>27146dc5-0ead-45bf-a67e-17b5d77c5a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5fabdb9d-3d67-4e62-898f-463cd27b85df']</value>
      <webElementGuid>e906b3ad-53ac-463b-87e9-f3f71643dc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>9dc57f5c-6048-4828-a049-f11835037ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>6cc1bc6f-7977-4e42-8967-c16f2b2bd174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '5fabdb9d-3d67-4e62-898f-463cd27b85df' and @name = 'shipping_postcode']</value>
      <webElementGuid>dd345733-aa54-4026-970c-7beb7c589a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
