<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addressstreet0</name>
   <tag></tag>
   <elementGuidId>d7f168ad-3780-483b-b202-b518c4cd6038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a4280be4-0d06-4da1-b5e0-9d717e62e911</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[4]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c96e19f-694b-4fb2-8443-a0a9fc80f9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>aea1f224-f9ab-4443-8b6f-bf6494cf671e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a4280be4-0d06-4da1-b5e0-9d717e62e911</value>
      <webElementGuid>11951f7d-280a-4704-8754-ceeee8c6bd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[street[0]]</value>
      <webElementGuid>c808f30e-8b58-464e-8917-ba36bdfb4d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>3b6140df-a39f-49b6-8cc0-df102409bd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a4280be4-0d06-4da1-b5e0-9d717e62e911&quot;)</value>
      <webElementGuid>8c7ddd34-d593-432c-872a-8c02e8632f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a4280be4-0d06-4da1-b5e0-9d717e62e911']</value>
      <webElementGuid>b0ae7741-23ed-419b-b8f6-b4e00c966bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[4]/div/span/input</value>
      <webElementGuid>e5575883-42f2-45a6-976f-03490c733b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>592a8fd6-54af-4883-87bd-45bc5359d05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'a4280be4-0d06-4da1-b5e0-9d717e62e911' and @name = 'shipping_address[street[0]]']</value>
      <webElementGuid>d213bda2-cbad-4473-b322-77e4d80deeae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
