<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addresslastname</name>
   <tag></tag>
   <elementGuidId>89ae4f13-eff2-4b31-bd0b-9d54a9b75693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7d71a0e0-12e3-49b9-b5e5-d377b81f227e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[2]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>138c338c-aa0d-4ff0-9ead-b5ad60ec3df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>66927c84-de05-42df-b63f-2b8cc2c3aade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7d71a0e0-12e3-49b9-b5e5-d377b81f227e</value>
      <webElementGuid>9f3ab8e4-6cb8-4c33-9757-c8ba3b4ebdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[lastname]</value>
      <webElementGuid>96b8e596-405b-497c-b271-a62245c419ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>D</value>
      <webElementGuid>5c714fd6-5fae-4f38-ae8d-34f20c3979ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7d71a0e0-12e3-49b9-b5e5-d377b81f227e&quot;)</value>
      <webElementGuid>65155471-1072-4279-9d48-ce881e5ea380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7d71a0e0-12e3-49b9-b5e5-d377b81f227e']</value>
      <webElementGuid>de21aa01-49d3-458d-9bb6-3fd50af9051f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>c5200c5b-f8e0-4956-87b6-7c19d12db4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>516731f2-37c2-401f-8f0e-81c6bcf2f62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7d71a0e0-12e3-49b9-b5e5-d377b81f227e' and @name = 'shipping_address[lastname]']</value>
      <webElementGuid>e44514cf-105d-449d-94e5-a3ddb6095f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
