<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tavs e-pasts_email</name>
   <tag></tag>
   <elementGuidId>8b501d1a-11fb-4280-9872-b2f0ccbd542c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ec34e843-6799-4774-a928-8d81ef5dbcfb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div/div/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93c0e236-282d-4a68-8cc2-a26fde2fbf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>d782bd07-e2f6-4b04-90e7-9b9307612a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec34e843-6799-4774-a928-8d81ef5dbcfb</value>
      <webElementGuid>a815e236-baaa-49f7-9ca0-23a3a94890a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2ef1c8bd-bb40-49bc-ac0d-5486b6cc38e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec34e843-6799-4774-a928-8d81ef5dbcfb&quot;)</value>
      <webElementGuid>ffb9bd71-b1bc-4f99-be32-b39788c7a3b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ec34e843-6799-4774-a928-8d81ef5dbcfb']</value>
      <webElementGuid>dc48f7c0-f41d-407f-ad43-e94d29634ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div/div/div/span/input</value>
      <webElementGuid>4f519252-d5da-451d-acac-7f1cffb48527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f50167f2-6af2-4cbc-9455-51f8c8d0ef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ec34e843-6799-4774-a928-8d81ef5dbcfb' and @name = 'email']</value>
      <webElementGuid>a1917a89-ca16-4fd9-9a37-dace4048cfd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
