<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_dau novads</name>
   <tag></tag>
   <elementGuidId>ff8ef136-aec1-4386-b690-d6c4951fb05b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='shipping_address[region_id]']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8c937d1e-c9ea-4a0a-9c76-bf0258158288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471</value>
      <webElementGuid>e0611983-6880-4f1e-b344-75d072cf62d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>92d29fc9-0a94-4be6-9a34-b684658fa504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f1c478f-0173-4537-96c8-92765b991ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>baf35a5b-d377-4011-b197-ad911c859078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ādažu novads</value>
      <webElementGuid>f690e8ef-7a17-4215-af09-f3f96d86f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471&quot;)</value>
      <webElementGuid>5fc59140-47ff-4230-9fc2-515695116c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471']</value>
      <webElementGuid>9c3154e7-c880-4530-afac-aa2360910cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_list-box']/li[2]</value>
      <webElementGuid>62e50011-cec4-49b8-8b7a-a9509789af25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novads'])[2]/following::li[1]</value>
      <webElementGuid>2476b6c5-e452-492f-abbf-0b3209701c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meklēt'])[2]/following::li[2]</value>
      <webElementGuid>946499a2-f49d-41ad-bbb0-71b53a7bf773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aglonas novads'])[2]/preceding::li[1]</value>
      <webElementGuid>960e8de6-4c9f-4fda-bc2f-92c63e844898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aizkraukles novads'])[2]/preceding::li[2]</value>
      <webElementGuid>e5f173cb-c15e-483c-b9d2-4cdba11a7683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/ul/li[2]</value>
      <webElementGuid>c67f0c4e-cf29-4b2b-8ea6-7737de2e3fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_471' and (text() = 'Ādažu novads' or . = 'Ādažu novads')]</value>
      <webElementGuid>8eb181e9-e655-4cae-8afd-a0fb5c73db4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
