<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>b79b2c59-08a8-494d-a860-58f5c0e36064</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-firstRow-3Qm&quot;]/ul[@class=&quot;header-buttons-31h&quot;]/li[@class=&quot;header-cart-RHA&quot;]/div[@class=&quot;cartTrigger-root-3-y&quot;]/a[@class=&quot;cartTrigger-trigger-2rF&quot;]/span[@class=&quot;icon-iconRoot-2hh&quot;]/svg[@class=&quot;iconHover&quot;]/path[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>85be56df-582a-41ff-be75-9d699c6caa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M16 10a4 4 0 0 1-8 0</value>
      <webElementGuid>1e98bfda-09f2-465d-ab4a-0c9ee436ae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-firstRow-3Qm&quot;]/ul[@class=&quot;header-buttons-31h&quot;]/li[@class=&quot;header-cart-RHA&quot;]/div[@class=&quot;cartTrigger-root-3-y&quot;]/a[@class=&quot;cartTrigger-trigger-2rF&quot;]/span[@class=&quot;icon-iconRoot-2hh&quot;]/svg[@class=&quot;iconHover&quot;]/path[2]</value>
      <webElementGuid>6954aa77-1bff-43bd-92a8-ee3202b27659</webElementGuid>
   </webElementProperties>
</WebElementEntity>
