<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TAVA VAJADZBA_menu-dropdownTrigger-1-s</name>
   <tag></tag>
   <elementGuidId>28410af1-e6e8-41f9-bf52-91ea82f8a203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div[2]/div[2]/ul/li[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-title-3KT.menu-hover-2ZV > a.text-small.text-upper.text-primary.menu-titleText-2Qo.menu-displayFirst-1Pg.link-never-vP7 > div.menu-dropdownTrigger-1-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0b2dc81-ed2a-4938-a9c8-cd23daaeead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-dropdownTrigger-1-s</value>
      <webElementGuid>5f805004-38d0-439a-8e7d-b553fb3df050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR header-fixed-3Fr&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-secondRow-1Wz&quot;]/ul[@class=&quot;menu-root-1cB&quot;]/li[@class=&quot;menu-title-3KT menu-hover-2ZV&quot;]/a[@class=&quot;text-small text-upper text-primary menu-titleText-2Qo menu-displayFirst-1Pg link-never-vP7&quot;]/div[@class=&quot;menu-dropdownTrigger-1-s&quot;]</value>
      <webElementGuid>949872cc-4e6a-4c5a-a597-20dae398e3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div[2]/ul/li[2]/a/div</value>
      <webElementGuid>ab165ff0-d63a-48d1-9703-e9197842bdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div</value>
      <webElementGuid>15017d4c-e441-42b8-bf95-26fd2b9dd1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
