<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>b61448af-4ad5-4d22-a94f-5079bb11147a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#90eaec63-0b33-466a-a395-7104531a39cf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='90eaec63-0b33-466a-a395-7104531a39cf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2dbfec1-9b06-468b-9385-2c84990a8132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>6792f742-06f5-47e3-8f18-16dcb3df955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>90eaec63-0b33-466a-a395-7104531a39cf</value>
      <webElementGuid>f3721288-fe7c-4a98-be3f-b296ecd78ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>22955fa6-3b8b-40cb-aecc-45b00d15c4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;90eaec63-0b33-466a-a395-7104531a39cf&quot;)</value>
      <webElementGuid>3d2fde8d-a725-4250-bf74-ab0496ce0691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='90eaec63-0b33-466a-a395-7104531a39cf']</value>
      <webElementGuid>e7e7d62d-84f6-491b-8426-e6d7d6d9dd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>4b5ba12c-a5d9-4104-bde5-0bf21766b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>cd48015c-fbb5-40a2-9913-5f6c1a0c95fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '90eaec63-0b33-466a-a395-7104531a39cf' and @name = 'shipping_postcode']</value>
      <webElementGuid>8cfaf5d6-a4b7-4acf-b74b-5cc4f62a1666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
