<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apstiprini piegdes veidu</name>
   <tag></tag>
   <elementGuidId>d6f2e1cc-009c-4cce-8e82-adc87459d98c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-primary-2sr.button-fullWidth-2zB</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'submit' and (text() = 'Apstiprini piegādes veidu' or . = 'Apstiprini piegādes veidu')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee3621e2-d410-4876-9067-7a944c1cb248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>72251408-6767-46ae-a773-ff1dec25205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-primary-2sr button-fullWidth-2zB</value>
      <webElementGuid>5e2c3ca2-4582-42c3-bd0b-5f9d0938759b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apstiprini piegādes veidu</value>
      <webElementGuid>f7eb7f1f-efba-4e11-9b56-896492b506a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;main-content-3U-&quot;]/div[@class=&quot;checkoutPage-root-1g1&quot;]/div[@class=&quot;checkoutPage-container-E0x&quot;]/div[@class=&quot;checkoutPage-main-2nO&quot;]/div[1]/div[2]/div[@class=&quot;checkoutStep-root-2-p&quot;]/div[@class=&quot;checkoutStep-content-bW9&quot;]/div[@class=&quot;loaderWrapper-root-PmU&quot;]/form[1]/button[@class=&quot;button-primary-2sr button-fullWidth-2zB&quot;]</value>
      <webElementGuid>3916e5ee-df41-41aa-b0e7-72cfed87f653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>de5e3b7c-17d6-4af4-a00a-a2af83df803e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/button</value>
      <webElementGuid>305e933e-3e2c-413a-b4b3-7e3396d6ea13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ilgtspējīgs'])[1]/following::button[1]</value>
      <webElementGuid>a672753d-c7ed-458f-b4c4-dd58ca334f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Est. delivery on Oct 05, 2022'])[3]/following::button[1]</value>
      <webElementGuid>fa7f9dd4-539a-4fd1-b8f0-7a9f90c683cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saņēmēja piegādes dati'])[1]/preceding::button[1]</value>
      <webElementGuid>14d4b892-827d-4e03-a28e-24160c7d7b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maksājuma detaļas'])[1]/preceding::button[1]</value>
      <webElementGuid>3f19ccb4-b252-4f82-b766-28a2f8917e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>6a1d9283-6c5d-471d-b801-032188676852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Apstiprini piegādes veidu' or . = 'Apstiprini piegādes veidu')]</value>
      <webElementGuid>c85a6527-55ae-440f-bc5a-28b6651ba6ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
