<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Es piekrtu Mjaslapas noteikumiem</name>
   <tag></tag>
   <elementGuidId>d6828126-c1f4-43eb-b181-deecc12f46bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkoutPage-tosWrapper-1KO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84558c2b-86d2-4538-9fb1-e9d7b1776ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkoutPage-tosWrapper-1KO</value>
      <webElementGuid>9bd0484c-5c53-4cdd-b003-1a064a4d6014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Es piekrītu Mājaslapas noteikumiem*</value>
      <webElementGuid>3a45844c-be0c-453f-8541-7da8f3a07d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;main-content-3U-&quot;]/div[@class=&quot;checkoutPage-root-1g1&quot;]/div[@class=&quot;checkoutPage-container-E0x&quot;]/div[@class=&quot;checkoutPage-main-2nO&quot;]/div[1]/div[2]/div[@class=&quot;checkoutPage-tosWrapper-1KO&quot;]</value>
      <webElementGuid>aabb2135-5618-4843-8772-9fb7a6a97bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[4]</value>
      <webElementGuid>443cbbaa-4b12-444c-a882-4ddfd9d964bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trustly'])[1]/following::div[2]</value>
      <webElementGuid>d4fa2382-de32-43ad-8487-a9653ddab9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal'])[1]/following::div[8]</value>
      <webElementGuid>ae2ac8b9-4b28-4ce0-b30d-7d4e48a42a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>5f6de990-5f70-4540-949f-2274e4deaa44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Es piekrītu Mājaslapas noteikumiem*' or . = 'Es piekrītu Mājaslapas noteikumiem*')]</value>
      <webElementGuid>935b0025-4aaf-4df4-8143-69cb5bc3c413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
