<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tavs e-pasts_email</name>
   <tag></tag>
   <elementGuidId>529bce13-3566-4f41-8218-3a11da6bb1fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9010f309-3cd1-45b9-9db4-7c8a45d6ff93</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a32df7b1-cafe-4415-8dee-0f052336cef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>1b931929-2a30-4aee-a192-698214980beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9010f309-3cd1-45b9-9db4-7c8a45d6ff93</value>
      <webElementGuid>5652bd69-69a1-4d3d-9076-2914d743b321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3593fae5-04b3-4ec0-a3ea-063cd7b509d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9010f309-3cd1-45b9-9db4-7c8a45d6ff93&quot;)</value>
      <webElementGuid>58f5cc11-954d-4a94-b47e-caaebd443764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9010f309-3cd1-45b9-9db4-7c8a45d6ff93']</value>
      <webElementGuid>9cf59508-aa48-43f3-a00f-27c19e8837f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div/div/div/span/input</value>
      <webElementGuid>7c2adfc6-a5b3-4355-aa2d-41f45072f44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>204bfbe9-7555-48ee-869d-3376f4891d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9010f309-3cd1-45b9-9db4-7c8a45d6ff93' and @name = 'email']</value>
      <webElementGuid>42dfcd68-7849-48f9-8d8f-c2fb139773df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
