<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>6362bfc3-b95f-4271-ac77-43e3a387f238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#46260bdb-e52f-4330-8db7-aeaffef19340</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10e52a4c-f881-4d17-baf2-e25ddb0cec8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>7dd3e759-06a4-482e-b935-5edc93c8007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>46260bdb-e52f-4330-8db7-aeaffef19340</value>
      <webElementGuid>04787105-8936-407d-8a51-13bb8cfcd0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>3feb189d-ac84-4859-a1af-cbb01fb33345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;46260bdb-e52f-4330-8db7-aeaffef19340&quot;)</value>
      <webElementGuid>1b135e39-97c7-4db9-80db-69151e572341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='46260bdb-e52f-4330-8db7-aeaffef19340']</value>
      <webElementGuid>972b79fb-d821-4db9-80e0-29308380850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>4d710540-2e40-4f83-ab3c-b631e541acef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b19212dd-07c0-4959-843b-af5e01c6a924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '46260bdb-e52f-4330-8db7-aeaffef19340' and @name = 'shipping_postcode']</value>
      <webElementGuid>a6f2b8e5-1c3d-4da6-a790-5464e7663686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
