<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addresslastname</name>
   <tag></tag>
   <elementGuidId>70235a16-5f78-4858-ae4a-6da9bfa79a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#49b7cac6-8ee7-4600-a3cd-28a27b8d2ec0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff38b443-8345-4b07-be2d-1b5ab4485c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>c03ff37e-f69d-418b-8502-4f35e1195703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>49b7cac6-8ee7-4600-a3cd-28a27b8d2ec0</value>
      <webElementGuid>49f8efec-e233-4e58-b075-67d1fac7fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[lastname]</value>
      <webElementGuid>3910d61c-6b91-4807-8957-c16b59df95f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>D</value>
      <webElementGuid>2d02c818-b2e7-471a-8ce4-37bb3ef46ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;49b7cac6-8ee7-4600-a3cd-28a27b8d2ec0&quot;)</value>
      <webElementGuid>4641bb3b-476d-4745-9e05-6a17838c6895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='49b7cac6-8ee7-4600-a3cd-28a27b8d2ec0']</value>
      <webElementGuid>38781532-3d69-4c22-bf81-5771c640ab83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>2d136808-8440-491c-b32e-0cc15d39fa65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>4b348d2b-7668-4738-bbe9-7162829c18aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '49b7cac6-8ee7-4600-a3cd-28a27b8d2ec0' and @name = 'shipping_address[lastname]']</value>
      <webElementGuid>b8c9bd77-d186-4711-b912-7c98b48bb074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
