<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Piegdes dati_shipping_addressfirstname</name>
   <tag></tag>
   <elementGuidId>b95ea6a7-765a-4225-afec-2395f0cdf7ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7576f3c0-bf92-484e-a552-a17034d0e2bb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1289eff0-2ee3-42a0-aa8e-1ff9d05ac30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>c145205c-f035-4ed4-934c-b0d76b9f4278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7576f3c0-bf92-484e-a552-a17034d0e2bb</value>
      <webElementGuid>7e8f835a-c0b2-4dd6-b884-b0dcd57ca124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[firstname]</value>
      <webElementGuid>af1ea615-ef1c-4b12-b643-a579d08d04df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7576f3c0-bf92-484e-a552-a17034d0e2bb&quot;)</value>
      <webElementGuid>98210c8c-caec-4071-9562-68110599f601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7576f3c0-bf92-484e-a552-a17034d0e2bb']</value>
      <webElementGuid>a2397e81-5f76-4eaf-a3b7-1e19b699b333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>f2c710a7-0989-4f15-841f-1be6729712a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/input</value>
      <webElementGuid>a4191331-32b8-4dd4-acc9-843cdb770048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7576f3c0-bf92-484e-a552-a17034d0e2bb' and @name = 'shipping_address[firstname]']</value>
      <webElementGuid>fa898f3a-cf6e-4e67-ba0b-1225d50af8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
