<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addressstreet0</name>
   <tag></tag>
   <elementGuidId>723aeac9-da3a-4eab-bdb3-11f5567a0d9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#19d9c65d-7189-4b57-b049-cafd88723f29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>567d45b2-3782-45a8-8cd7-6c63c9f6190f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>9f06f267-d6af-43d4-8784-733632266310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>19d9c65d-7189-4b57-b049-cafd88723f29</value>
      <webElementGuid>1e795ab2-2deb-450e-a0c0-9d24f6bb3466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[street[0]]</value>
      <webElementGuid>e3f43856-e3c4-4e9c-9a40-7003df4c6324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;19d9c65d-7189-4b57-b049-cafd88723f29&quot;)</value>
      <webElementGuid>1f5f0aa8-8300-4213-ad00-aa727b1c6ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='19d9c65d-7189-4b57-b049-cafd88723f29']</value>
      <webElementGuid>9c0a4787-6dcb-476f-8339-561e690df142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[4]/div/span/input</value>
      <webElementGuid>94b19e98-97f7-4c3c-b910-e586ad553d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>bee5033f-238a-4cb4-be02-a58054bc4e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '19d9c65d-7189-4b57-b049-cafd88723f29' and @name = 'shipping_address[street[0]]']</value>
      <webElementGuid>545a7a63-c77f-4f30-878b-7f4e9379cdfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
