<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Aizputes novads</name>
   <tag></tag>
   <elementGuidId>32b4d6ee-d64e-4110-b8ea-9614e7aee044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00ea702a-d58f-4526-bed8-5672365ef995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368</value>
      <webElementGuid>22fe1a39-574f-4369-a212-69c1959ae5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f739b95e-2f56-4f58-8907-52491f392044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>178970d2-b3f0-4b6b-8901-60f519f759ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S-</value>
      <webElementGuid>56c8474a-d382-4b82-a7af-8d48ec317b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aizputes novads</value>
      <webElementGuid>e8fc6c93-8139-40ba-b397-4ae41abc42bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368&quot;)</value>
      <webElementGuid>12925372-9699-42dd-a5cf-264dd0b3d49c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368']</value>
      <webElementGuid>f7285bdf-8fd6-4eb3-8d74-4dee1f7275fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_list-box']/li[5]</value>
      <webElementGuid>8b873697-e22d-4716-b155-48bb2421fe71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aizkraukles novads'])[2]/following::li[1]</value>
      <webElementGuid>5f862303-a691-4408-ba95-9a35784bdaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aglonas novads'])[2]/following::li[2]</value>
      <webElementGuid>7a62f10e-4e49-4ecb-b9c6-fd6744074b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aknīstes novads'])[2]/preceding::li[1]</value>
      <webElementGuid>dfd9f31e-9b7f-4c85-9185-da996ce8a982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alojas novads'])[2]/preceding::li[2]</value>
      <webElementGuid>de906f80-c31f-46f0-9505-35e99e886465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/ul/li[5]</value>
      <webElementGuid>7c471bce-d32b-471c-88ee-e6cb109ec005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c2hpcHBpbmdfYWRkcmVzc1tyZWdpb25faWRd_368' and (text() = 'Aizputes novads' or . = 'Aizputes novads')]</value>
      <webElementGuid>1d5826ce-a137-4e96-bd35-7429c2c16c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
