<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Card Number_paymentcc_number</name>
   <tag></tag>
   <elementGuidId>42d2ed5b-6884-418e-8023-48f3890033c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rootways_authorizecim_option_cc_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rootways_authorizecim_option_cc_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15dd3015-1a8c-4b93-80da-c554a11a403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>72170799-9348-4cc0-9eb9-d16995e8214d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[cc_number]</value>
      <webElementGuid>225ed5fd-8a45-466c-a574-20ce14470c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>7e6aff58-c773-433d-ad52-34c87f9f4ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>1dbf336b-9068-493e-beb3-f68ca2547252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>93e25ada-cf67-4864-88c1-2310a7f2a15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>6a1f21e7-4bb0-4451-8c09-3d6849c218c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { autocomplete: off, id: getCode() + '_cc_number', title: $t('Credit Card Number'), 'data-container': getCode() + '-cc-number', 'data-validate': JSON.stringify({'required-number':true, 'validate-card-type':getCcAvailableTypesValues(), 'validate-card-number':'#' + getCode() + '_cc_type', 'validate-cc-type':'#' + getCode() + '_cc_type'})}, enable: isActive($parents), value: creditCardNumber, valueUpdate: 'keyup' </value>
      <webElementGuid>4ffe498e-192e-466f-a5b5-df83204d1d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>function(ns){var storage=getEvents(this);if(!storage){return this;}
storage.forEach(function(handlers,name){handlers=handlers.filter(function(handler){return!ns?false:handler.ns!==ns;});handlers.length?storage.set(name,handlers):storage.delete(name);});return this;}</value>
      <webElementGuid>203000d8-3d32-4efa-ac19-3e5ad1f937ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootways_authorizecim_option_cc_number</value>
      <webElementGuid>649f6671-ccd9-4415-a191-8f718cb921ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Credit Card Number</value>
      <webElementGuid>96695a61-486a-497c-be1a-d7591201e84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>rootways_authorizecim_option-cc-number</value>
      <webElementGuid>195001aa-d647-442f-9187-6a262c5220fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required-number&quot;:true,&quot;validate-card-type&quot;:[{&quot;value&quot;:&quot;AE&quot;,&quot;type&quot;:&quot;American Express&quot;},{&quot;value&quot;:&quot;VI&quot;,&quot;type&quot;:&quot;Visa&quot;},{&quot;value&quot;:&quot;MC&quot;,&quot;type&quot;:&quot;MasterCard&quot;},{&quot;value&quot;:&quot;DI&quot;,&quot;type&quot;:&quot;Discover&quot;}],&quot;validate-card-number&quot;:&quot;#rootways_authorizecim_option_cc_type&quot;,&quot;validate-cc-type&quot;:&quot;#rootways_authorizecim_option_cc_type&quot;}</value>
      <webElementGuid>d8befe23-3211-428d-8939-0f60064792f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb82c303-6029-4fe1-bb04-291c7585a8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootways_authorizecim_option_cc_number&quot;)</value>
      <webElementGuid>d617f572-1d6d-4a96-b15a-2657292171c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rootways_authorizecim_option_cc_number']</value>
      <webElementGuid>8fa7c510-0c70-4301-b4b1-521a546a02da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='payment_form_rootways_authorizecim_option']/div[2]/div/input</value>
      <webElementGuid>5fb7a347-44c2-4b1a-8d41-c62843d31e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/fieldset/div[2]/div/input</value>
      <webElementGuid>509914ef-188e-4877-80c4-cb48ce98143c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'payment[cc_number]' and @id = 'rootways_authorizecim_option_cc_number' and @title = 'Credit Card Number']</value>
      <webElementGuid>a924822f-f950-4bc0-9396-8a9728f47de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
