<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Verification Number_paymentcc_cid</name>
   <tag></tag>
   <elementGuidId>96b27646-a0a9-46dc-991d-c089d92dc661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rootways_authorizecim_option_cc_cid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rootways_authorizecim_option_cc_cid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8778687d-abdd-442a-ab67-61b7e590658d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2018c574-5d59-47da-b39f-116d2fa8b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b850f130-2680-4085-b675-6e523ac53c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text cvv</value>
      <webElementGuid>bf7bce60-f41d-4da7-b56e-4db5006b4cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[cc_cid]</value>
      <webElementGuid>af600e0d-e603-496e-b8c6-dbc6a5e2ec32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>68cde6f5-2a31-40ea-a540-71d8f5148a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>1cf96c1f-f691-4b61-8d27-ba8f87dfc205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>23984f3f-f927-4d8a-9b47-ee33343d53b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: getCode() + '_cc_cid', title: $t('Card Verification Number'), 'data-container': getCode() + '-cc-cvv', 'data-validate': JSON.stringify({'required-number':true, 'validate-card-cvv':'#' + getCode() + '_cc_type'})}, enable: isActive($parents), value: creditCardVerificationNumber</value>
      <webElementGuid>e2679382-36b7-4075-b452-015023e5e476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootways_authorizecim_option_cc_cid</value>
      <webElementGuid>ac34d3bf-1e32-44f3-8ed2-a639020cc59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Card Verification Number</value>
      <webElementGuid>1f5bf706-91bf-46b1-9607-38ea3a6daa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>rootways_authorizecim_option-cc-cvv</value>
      <webElementGuid>71811e66-80b4-402b-8b71-ec3e01746f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required-number&quot;:true,&quot;validate-card-cvv&quot;:&quot;#rootways_authorizecim_option_cc_type&quot;}</value>
      <webElementGuid>fc9a7ae8-313b-4145-bb24-558f5ffac597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55a5d756-d289-4925-a611-92288b42b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootways_authorizecim_option_cc_cid&quot;)</value>
      <webElementGuid>2a262252-1572-4b73-9c12-7c0a9214dfb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rootways_authorizecim_option_cc_cid']</value>
      <webElementGuid>1d1f446d-686a-4fd1-a5b5-810e8c68c1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootways_authorizecim_option_cc_type_cvv_div']/div/input</value>
      <webElementGuid>769815e0-d52e-4c17-b845-0579a69a5374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/fieldset/div[4]/div/input</value>
      <webElementGuid>5d8fb397-a8e1-4bca-9cf4-60410dc9cef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'payment[cc_cid]' and @id = 'rootways_authorizecim_option_cc_cid' and @title = 'Card Verification Number']</value>
      <webElementGuid>5245b309-7c8d-4591-9a15-e1741f8dd8d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
