<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment Method_paymentmethod</name>
   <tag></tag>
   <elementGuidId>0e6f2342-13d7-4f86-8b5a-b9b9e96af12b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootways_authorizecim_option_wrapper']/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rootways_authorizecim_option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5efb5cca-f025-4e21-ab83-edb55f7161d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fa3f5c3e-e009-4128-ac57-4af5e08ae167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[method]</value>
      <webElementGuid>c8c85597-5669-49a9-9131-2eea3a6e5911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>26cca2df-b0ed-415c-b324-c9f69b54a3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'id': getCode()}, value: getCode(), checked: isChecked, click: selectPaymentMethod, visible: isRadioButtonVisible()</value>
      <webElementGuid>024fb445-4243-47ce-8e9f-b403aec0074a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootways_authorizecim_option</value>
      <webElementGuid>a095f956-7d6a-49f4-b27b-1fc1831e7fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rootways_authorizecim_option</value>
      <webElementGuid>e185a6bc-4bcd-4098-82e1-c22d1485a66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootways_authorizecim_option&quot;)</value>
      <webElementGuid>dda99f8e-7de7-488a-b3d6-13e488f68628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rootways_authorizecim_option']</value>
      <webElementGuid>00ee0625-68cf-4f22-8b2d-fbc1d40c6860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootways_authorizecim_option_wrapper']/div/input</value>
      <webElementGuid>d341f825-b0b6-4767-8849-dc4825141c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>45069ff3-f37c-44e9-9ab5-d342de7c50ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment[method]' and @id = 'rootways_authorizecim_option']</value>
      <webElementGuid>7fa28d92-123e-4b08-b2ff-0f18e7ad1c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
