<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year20222023202420252026202720282029_dc5189</name>
   <tag></tag>
   <elementGuidId>b636a82f-33ef-42ff-ae81-f8ceaa241e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rootways_authorizecim_option_expiration_yr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rootways_authorizecim_option_expiration_yr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9adefcce-4e36-4f95-8508-653c3e932e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[cc_exp_year]</value>
      <webElementGuid>e365db86-cf46-48fc-85f9-f27ad876baf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-year</value>
      <webElementGuid>6910fe2c-3a8b-46ed-8dc4-0060a6ddf02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: getCode() + '_expiration_yr', 'data-container': getCode() + '-cc-year', 'data-validate': JSON.stringify({required:true})}, enable: isActive($parents), options: getCcYearsValues(), optionsValue: 'value', optionsText: 'year', optionsCaption: $t('Year'), value: creditCardExpYear</value>
      <webElementGuid>e0a49aa5-db99-4d76-bda5-e96f4d836ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootways_authorizecim_option_expiration_yr</value>
      <webElementGuid>5a5c9c7b-2fb2-416c-9e32-1a893b56cc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>rootways_authorizecim_option-cc-year</value>
      <webElementGuid>d54ebcdc-92c1-45af-8fcc-815851235f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required&quot;:true}</value>
      <webElementGuid>25cc0a54-2931-43d1-a67d-38b60bbb67ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ec8b6aa-ba3d-4689-8357-01c9e75ca0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year20222023202420252026202720282029203020312032</value>
      <webElementGuid>4e44c8df-950e-457f-90cd-cfad3f5e442b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootways_authorizecim_option_expiration_yr&quot;)</value>
      <webElementGuid>a0fbd7fd-db79-4b1f-9bd7-dccc48f836a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rootways_authorizecim_option_expiration_yr']</value>
      <webElementGuid>def1f7c8-cf8d-427f-af04-db6dc6376ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootways_authorizecim_option_cc_type_exp_div']/div/div/div[2]/div/select</value>
      <webElementGuid>1ce5b34b-d471-4c9c-92f4-1f5b035262c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[1]/following::select[2]</value>
      <webElementGuid>91dbdab4-3b6d-4d6d-8283-be33d13cfa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card Number'])[1]/following::select[2]</value>
      <webElementGuid>6e39ca6e-ba24-4b65-9c5d-4535367fb4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Verification Number'])[1]/preceding::select[1]</value>
      <webElementGuid>3e6c93e9-3be3-4152-9e8e-0577234792ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is this?'])[1]/preceding::select[1]</value>
      <webElementGuid>d9eca54f-d51a-4ab3-b71d-f593efccc6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b0231fde-88f4-4ad0-b305-92be4bf64cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'payment[cc_exp_year]' and @id = 'rootways_authorizecim_option_expiration_yr' and (text() = 'Year20222023202420252026202720282029203020312032' or . = 'Year20222023202420252026202720282029203020312032')]</value>
      <webElementGuid>3a615d26-dc62-4314-9015-035e9abbadfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
