<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month01 - January02 - February03 - M_2fae30</name>
   <tag></tag>
   <elementGuidId>374de431-827c-4658-866c-5630b8140dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rootways_authorizecim_option_expiration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rootways_authorizecim_option_expiration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4583a428-b67f-4064-95a1-b1811e5bbbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[cc_exp_month]</value>
      <webElementGuid>d2567c74-ca1e-446f-8dca-6a48021bfe53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select select-month</value>
      <webElementGuid>120b147c-9cd7-403e-a5af-0dbadb75c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: getCode() + '_expiration', 'data-container': getCode() + '-cc-month', 'data-validate': JSON.stringify({required:true, 'validate-cc-exp':'#' + getCode() + '_expiration_yr'})}, enable: isActive($parents), options: getCcMonthsValues(), optionsValue: 'value', optionsText: 'month', optionsCaption: $t('Month'), value: creditCardExpMonth</value>
      <webElementGuid>61c43c52-cd4f-4bd3-99d3-1c10ccd2f888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rootways_authorizecim_option_expiration</value>
      <webElementGuid>5cd41873-7263-4677-8468-aac8cdc407e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>rootways_authorizecim_option-cc-month</value>
      <webElementGuid>8690b644-e510-4f90-90ea-b0837b2ccd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required&quot;:true,&quot;validate-cc-exp&quot;:&quot;#rootways_authorizecim_option_expiration_yr&quot;}</value>
      <webElementGuid>705a6f2d-39ee-4366-aeaa-2e604a44e0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8532c0c8-b1ee-4c93-9183-9b7a796542ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month01 - January02 - February03 - March04 - April05 - May06 - June07 - July08 - August09 - September10 - October11 - November12 - December</value>
      <webElementGuid>bc22c6b4-99a1-445d-ace7-5bddd5a83696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootways_authorizecim_option_expiration&quot;)</value>
      <webElementGuid>f619292c-9874-45c3-8b89-c8be727f6a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rootways_authorizecim_option_expiration']</value>
      <webElementGuid>ef17f210-a1d5-4554-850d-ca28198a8d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootways_authorizecim_option_cc_type_exp_div']/div/div/div/div/select</value>
      <webElementGuid>4aa8cc75-68ad-4981-a3bb-e3f639357fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[1]/following::select[1]</value>
      <webElementGuid>9344af99-e979-463c-98ad-a0ea6c7e19ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card Number'])[1]/following::select[1]</value>
      <webElementGuid>29b9af75-ad0d-49de-9e57-969a66d0bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Verification Number'])[1]/preceding::select[2]</value>
      <webElementGuid>afadf14f-2f86-4c83-ab37-40f3fa08d585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is this?'])[1]/preceding::select[2]</value>
      <webElementGuid>582c65e7-497e-43b3-b2f8-d15c23043514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/select</value>
      <webElementGuid>64418fab-0ada-491f-bc3e-4297ed5555aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'payment[cc_exp_month]' and @id = 'rootways_authorizecim_option_expiration' and (text() = 'Month01 - January02 - February03 - March04 - April05 - May06 - June07 - July08 - August09 - September10 - October11 - November12 - December' or . = 'Month01 - January02 - February03 - March04 - April05 - May06 - June07 - July08 - August09 - September10 - October11 - November12 - December')]</value>
      <webElementGuid>5c9ef265-4932-4053-9938-481e2360ff5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
