<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_United StatesAustraliaCanadaU.S. Out_a796f6</name>
   <tag></tag>
   <elementGuidId>5d615441-0716-4704-91a8-bd6c5e7f4fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shipping-new-address-form']/div[5]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NFF4LWJ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e420b0c3-9499-4067-a1f1-efe04209c01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb7314ad-2f2b-4975-85e6-773f4efda4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value> attr: { name: inputName, id: uid, disabled: disabled, 'aria-describedby': getDescriptionId(), 'aria-required': required, 'aria-invalid': error() ? true : 'false', placeholder: placeholder }, hasFocus: focused, optgroup: options, value: value, optionsCaption: caption, optionsValue: 'value', optionsText: 'label', optionsAfterRender: function(option, item) { if (item &amp;&amp; item.disabled) { ko.applyBindingsToNode(option, {attr: {disabled: true}}, item); } }</value>
      <webElementGuid>3b8beb8c-4444-4af9-9f97-b9490758a6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country_id</value>
      <webElementGuid>00dad4be-ae49-4eaa-ab59-57cffb940671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NFF4LWJ</value>
      <webElementGuid>16da4c88-8a7f-482d-a05a-d73e52b9eadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f492937-c456-44f3-aeaa-186be83d027c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b99e4f5d-937e-4562-99ed-66a338427791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> United States──────────AustraliaCanadaU.S. Outlying IslandsU.S. Virgin Islands</value>
      <webElementGuid>a951cec3-2a7c-4d16-97d7-17b59e753c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NFF4LWJ&quot;)</value>
      <webElementGuid>d69e0bb6-e4b7-443e-8fcc-e8615df6bedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NFF4LWJ']</value>
      <webElementGuid>f93d9d84-7328-4813-b91e-0c6d4a6f34f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping-new-address-form']/div[5]/div/select</value>
      <webElementGuid>0f477906-d5df-4017-b7b3-cdc700c7d7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
      <webElementGuid>62940d52-9f09-40cb-9ebd-c7c106ec12a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>e9a7989a-b3d2-4a3e-9bc5-263d53b12c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State/Province'])[1]/preceding::select[1]</value>
      <webElementGuid>0daf34ab-a0a3-438a-b47c-4f4ba7c759a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State/Province'])[2]/preceding::select[2]</value>
      <webElementGuid>41db0932-33e7-45eb-ad43-3ec3c53e3238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1ff7657f-a2e3-44fd-8fff-17e2215f5ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'country_id' and @id = 'NFF4LWJ' and (text() = ' United States──────────AustraliaCanadaU.S. Outlying IslandsU.S. Virgin Islands' or . = ' United States──────────AustraliaCanadaU.S. Outlying IslandsU.S. Virgin Islands')]</value>
      <webElementGuid>28ea493b-f348-4145-af20-381779160a4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
