<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addresslastname</name>
   <tag></tag>
   <elementGuidId>e99708bf-e731-4d04-b845-05a4df460387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f1c208dd-8b84-435c-8967-898d011e7861</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f1c208dd-8b84-435c-8967-898d011e7861']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c62ccfff-3cf4-4713-a644-77b36df1719b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>ead54800-05a5-4ec4-9988-21054508eef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f1c208dd-8b84-435c-8967-898d011e7861</value>
      <webElementGuid>2f883848-c24f-4faa-8457-82efcfc19da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[lastname]</value>
      <webElementGuid>c1e67fae-d1a5-4897-9a4c-0868e0306c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>D</value>
      <webElementGuid>98dda5eb-16f8-44ce-b20e-e551656add3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f1c208dd-8b84-435c-8967-898d011e7861&quot;)</value>
      <webElementGuid>0eaf7c90-94a0-4002-b259-1137d52edb44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f1c208dd-8b84-435c-8967-898d011e7861']</value>
      <webElementGuid>e7f93ad5-77ff-464a-8aa1-ed49fb015926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>5ff3d5b3-2a13-48ec-b6c8-b2a44d53811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>0f5176ea-bf9e-4bb3-b163-d998b640fdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f1c208dd-8b84-435c-8967-898d011e7861' and @name = 'shipping_address[lastname]']</value>
      <webElementGuid>1c9d6148-a2fa-4271-8236-8c6ae73ae006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
