<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_addressstreet0</name>
   <tag></tag>
   <elementGuidId>0a6a4724-9468-4b99-b31c-32e2f2614281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#764537ef-e40e-4435-8c40-a57a6627772c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='764537ef-e40e-4435-8c40-a57a6627772c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89961d6d-4343-41a3-9520-18c2725d085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>a1fefcaa-0d24-4b0b-91d7-adf1c5419966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>764537ef-e40e-4435-8c40-a57a6627772c</value>
      <webElementGuid>9df4f18c-3cab-4b81-982d-eded66d506f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address[street[0]]</value>
      <webElementGuid>01ef4723-3fdf-4d9c-9d96-cd99f3c13fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;764537ef-e40e-4435-8c40-a57a6627772c&quot;)</value>
      <webElementGuid>ffe66889-c188-4a2e-8568-88a7f54c2d46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='764537ef-e40e-4435-8c40-a57a6627772c']</value>
      <webElementGuid>3c2a9504-cac7-475c-9023-0da51234f8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/form/div[2]/div/div/div[4]/div/span/input</value>
      <webElementGuid>1f324193-a2c6-4fb8-a8cb-1a2baba29730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>51b8d7a0-0b46-438a-8f01-7d9dab8cda8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '764537ef-e40e-4435-8c40-a57a6627772c' and @name = 'shipping_address[street[0]]']</value>
      <webElementGuid>90d4d9d1-3e84-4afe-a9f0-89dde7c9dfeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
