<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__shipping_postcode</name>
   <tag></tag>
   <elementGuidId>2d060599-1f65-4934-ba32-2a06eb157405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#220246a3-ec55-476e-9b2b-b9321fbda81a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='220246a3-ec55-476e-9b2b-b9321fbda81a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08f23e8c-c419-40da-8f73-00c03e958dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput-input-30f</value>
      <webElementGuid>808f98b4-be62-421c-a134-e76371fe2935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>220246a3-ec55-476e-9b2b-b9321fbda81a</value>
      <webElementGuid>24b097f9-4c40-466b-9c33-766406a78710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>4597360a-ed0c-4537-828f-003d555fb7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;220246a3-ec55-476e-9b2b-b9321fbda81a&quot;)</value>
      <webElementGuid>143ee473-0e50-4082-b89f-1facded42f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='220246a3-ec55-476e-9b2b-b9321fbda81a']</value>
      <webElementGuid>da3183f4-8646-48f2-a9e7-bfb547ab8eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/span/input</value>
      <webElementGuid>e05f2b95-4d17-40ee-8038-939919dc3226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>28e65d47-a6bd-4ac9-9c28-9f7dfd7f3d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '220246a3-ec55-476e-9b2b-b9321fbda81a' and @name = 'shipping_postcode']</value>
      <webElementGuid>fed5cddf-75fd-4a94-90f2-b99f79098bb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
