<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Maksjuma detaas_icon-icon-2oA</name>
   <tag></tag>
   <elementGuidId>ddd377b9-0ff1-4735-bf49-01ddaa6622af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon.radioGroup-icon-X-k > span.icon-iconRoot-2hh > svg.icon-icon-2oA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Maksājuma detaļas'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>1060b711-6a07-4be7-b1a5-a47feb8df159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>feed6a25-bcff-4d2b-b8f7-50cdbe972ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>1c7c7ecc-cd49-43be-a93e-019be753aeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>1839a600-e950-4ef4-b844-2f0b521cae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>57a873e6-1e14-4f35-beac-a096e1924763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>517bda65-416d-49bd-adcd-ee7378389e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b6e35846-5b14-4535-96cd-cfc204b74b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>40abacdd-b29e-4137-b05d-b3ab5fbb4b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>4eeeb3c6-7272-4d2b-a412-d069829d1781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>c99cab32-a5b6-41f9-bb0e-28d4b3ab8c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-icon-2oA</value>
      <webElementGuid>ec53180b-bd55-4352-961c-a031dc87e427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;main-content-3U-&quot;]/div[@class=&quot;checkoutPage-root-1g1&quot;]/div[@class=&quot;checkoutPage-container-E0x&quot;]/div[@class=&quot;checkoutPage-main-2nO&quot;]/div[1]/div[2]/div[@class=&quot;checkoutStep-root-2-p&quot;]/div[@class=&quot;checkoutStep-content-bW9&quot;]/form[1]/label[@class=&quot;radioGroup-root-2Tl&quot;]/div[@class=&quot;icon radioGroup-icon-X-k&quot;]/span[@class=&quot;icon-iconRoot-2hh&quot;]/svg[@class=&quot;icon-icon-2oA&quot;]</value>
      <webElementGuid>fed729d8-da5c-46ab-90f1-89160fb94e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maksājuma detaļas'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0b576bb6-97f7-4d7f-968d-1e1c5f45a087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saņēmēja piegādes dati'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>aed72008-715b-4b08-80e8-f6c55bde5525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e657734d-740b-411d-855c-c56d10a27826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nākamajā solī tiks pieprasīta kredītkartes informācija'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f1334256-02be-42ea-a326-a5b3aebe207a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
