<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__text-primary visualSwatch-tile-TlL</name>
   <tag></tag>
   <elementGuidId>1b8dfd88-6746-44ca-86f3-3dc859d17b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@style = 'background-image: url(&quot;/cdn-cgi/image/format=auto,width=30,fit=cover/media/attribute/swatch/t/h/the-concealer-65-mocha.png&quot;); background-position: center center;']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1fb1535-aa43-441b-a248-5eac51ef7113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary visualSwatch-tile-TlL</value>
      <webElementGuid>da674ffc-0f6b-4cc9-a5de-4001afb6dc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>333adeef-cd34-422d-a297-f79c2aa662b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;main-content-3U-&quot;]/div[@class=&quot;productPage-root-2wd&quot;]/div[@class=&quot;productPage-main-2sY&quot;]/section[@class=&quot;productPage-section-2py productPage-productInformation-UOA&quot;]/div[@class=&quot;productPage-options-34d&quot;]/div[1]/div[@class=&quot;visualSwatch-root-3JF&quot;]/button[@class=&quot;text-primary visualSwatch-tile-TlL&quot;]</value>
      <webElementGuid>a6a7e858-e520-465a-8f0f-d9515feae7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>background-image: url(&quot;/cdn-cgi/image/format=auto,width=30,fit=cover/media/attribute/swatch/t/h/the-concealer-65-mocha.png&quot;); background-position: center center;</value>
      <webElementGuid>2810ab35-e5c2-455b-9352-568d2fdbfae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>80a65761-5884-4b45-a0d9-1c67363e0cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/section[3]/div[4]/div/div/button[10]</value>
      <webElementGuid>7d660185-38ee-4be2-90f2-c074780d5b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[10]</value>
      <webElementGuid>9decc637-9197-4734-8b43-55c1c5c3a9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>d84dcfb8-a2ef-4cb5-9325-4001c71b76bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
