<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Latvija</name>
   <tag></tag>
   <elementGuidId>d4ba7eb0-2f2d-4b1a-b9ba-ef0a1d851189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Y291bnRyeQ_LV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Y291bnRyeQ_LV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>caabfab1-ebf3-4134-9af1-8a66f1eb9278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Y291bnRyeQ_LV</value>
      <webElementGuid>b33582f3-cde6-40a4-b65d-47ebd67b121f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f6072555-a2e0-4d4b-b371-138d2cfcfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d491921-d096-4d34-abd3-4751ba99b9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S- select-customOptionSelected-19F</value>
      <webElementGuid>d953dd34-23d6-4a7a-96e4-df52a9ec0053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latvija</value>
      <webElementGuid>358316c2-1737-4ade-a2fd-641078fec195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR header-fixed-3Fr header-transparent-1s3&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-firstRow-3Qm&quot;]/ul[@class=&quot;header-buttons-31h&quot;]/li[@class=&quot;header-storeSwitcher-3rS&quot;]/div[@class=&quot;storeSwitcher-root-P9n&quot;]/aside[1]/div[@class=&quot;storeSwitcher-menu_open-N9p&quot;]/form[@class=&quot;storeSwitcher-form-3Cr&quot;]/div[1]/div[@class=&quot;field-root-1hC&quot;]/div[@class=&quot;select-root-2nI&quot;]/div[@class=&quot;select-customOptions-3Nu select-customOptionsOpen-3KZ&quot;]/div[@class=&quot;select-optionContainer-35C&quot;]/ul[@id=&quot;Y291bnRyeQ_list-box&quot;]/li[@id=&quot;Y291bnRyeQ_LV&quot;]</value>
      <webElementGuid>d379df52-03fc-40ad-b608-e58ac667d58f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='Y291bnRyeQ_LV']</value>
      <webElementGuid>1f991f68-79bb-4e7c-9fc0-1ee93da6f1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Y291bnRyeQ_list-box']/li[8]</value>
      <webElementGuid>8489dd74-5492-4718-9fbc-9c9810c657ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italia'])[2]/following::li[1]</value>
      <webElementGuid>0eedfcd0-cd74-4cd9-880f-0711b2a4695b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='France'])[2]/following::li[2]</value>
      <webElementGuid>d6be99c7-26fa-4706-9921-5bcaf2eb157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lietuva'])[2]/preceding::li[1]</value>
      <webElementGuid>370efffd-29d0-4d16-b140-289b4b17a56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nederland'])[2]/preceding::li[2]</value>
      <webElementGuid>9bf5e08c-a425-4485-bbd2-65cbf05c9fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>7801d6a7-5660-4880-9126-c31a1b18952f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'Y291bnRyeQ_LV' and (text() = 'Latvija' or . = 'Latvija')]</value>
      <webElementGuid>1c75e7b6-5d13-4e88-b3cb-ca3d3151cd78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
