<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Latvieu</name>
   <tag></tag>
   <elementGuidId>956fab42-f400-4c71-8403-1da1b7391577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='c3RvcmU_lv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c3RvcmU_lv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c369b373-29e4-4a37-adb2-e24e5e141f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3RvcmU_lv</value>
      <webElementGuid>0dab2aa8-c835-40ca-9e16-79dda6756916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>921f1090-45b0-44ae-8ca9-18899d70159b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7018c81-5850-4b53-a4e4-b4678347f64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-customOption-2S- select-customOptionSelected-19F</value>
      <webElementGuid>e73c668d-dafa-4d9d-8500-ec20a779fa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latviešu</value>
      <webElementGuid>4849624b-9790-4a0c-bc46-a1c9cffab50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR header-fixed-3Fr header-transparent-1s3&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-firstRow-3Qm&quot;]/ul[@class=&quot;header-buttons-31h&quot;]/li[@class=&quot;header-storeSwitcher-3rS&quot;]/div[@class=&quot;storeSwitcher-root-P9n&quot;]/aside[1]/div[@class=&quot;storeSwitcher-menu_open-N9p&quot;]/form[@class=&quot;storeSwitcher-form-3Cr&quot;]/div[1]/div[@class=&quot;field-root-1hC&quot;]/div[@class=&quot;select-root-2nI&quot;]/div[@class=&quot;select-customOptions-3Nu select-customOptionsOpen-3KZ&quot;]/div[@class=&quot;select-optionContainer-35C&quot;]/ul[@id=&quot;c3RvcmU_list-box&quot;]/li[@id=&quot;c3RvcmU_lv&quot;]</value>
      <webElementGuid>3d89d789-e424-47f6-9252-6bbf3b78ed88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='c3RvcmU_lv']</value>
      <webElementGuid>baf6c130-17bd-4e4a-9a25-a6ce80762ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='c3RvcmU_list-box']/li[2]</value>
      <webElementGuid>645a0e3a-f5bd-4085-85f0-18d225876a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valoda'])[2]/following::li[1]</value>
      <webElementGuid>589800e5-0817-4280-a5d3-e33f0fa41e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::li[2]</value>
      <webElementGuid>6bf2fb50-4283-429b-9992-953e8d45c317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Русский'])[2]/preceding::li[1]</value>
      <webElementGuid>c6302771-e552-4be8-9926-5749ce9c1e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/ul/li[2]</value>
      <webElementGuid>a1535ce2-c6f8-404f-98ef-7bda470d0447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'c3RvcmU_lv' and (text() = 'Latviešu' or . = 'Latviešu')]</value>
      <webElementGuid>c13e88ee-7bc3-4a0f-9440-f8dde37ae2b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
