<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Latvieu</name>
   <tag></tag>
   <elementGuidId>b534a8d2-a95b-45d2-8c7c-193e669a3247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div[2]/div/ul[2]/li[4]/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.storeSwitcher-language-wCq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6af0db3-baa4-44c9-99b7-02667196500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>storeSwitcher-language-wCq</value>
      <webElementGuid>22a8ebc0-8c62-45a0-ba47-8e6aed43edb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latviešu</value>
      <webElementGuid>b6563f7b-cb18-4b06-bdb8-730b873e0586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2dz&quot;]/div[@class=&quot;header-root-3zR header-fixed-3Fr header-transparent-1s3&quot;]/div[@class=&quot;header-wrapper-3hG&quot;]/div[@class=&quot;header-content-1wQ&quot;]/div[@class=&quot;header-firstRow-3Qm&quot;]/ul[@class=&quot;header-buttons-31h&quot;]/li[@class=&quot;header-storeSwitcher-3rS&quot;]/div[@class=&quot;storeSwitcher-root-P9n&quot;]/button[@class=&quot;storeSwitcher-trigger-1L7&quot;]/span[@class=&quot;storeSwitcher-language-wCq&quot;]</value>
      <webElementGuid>fa5c1504-295b-4399-99d4-3dd2346f1b6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div/ul[2]/li[4]/div/button/span[2]</value>
      <webElementGuid>d55f99e1-439d-43b9-a8f8-5126887ab483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profils'])[1]/following::span[2]</value>
      <webElementGuid>ecad5755-46e8-457c-9e25-1a878b6e5e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atvērt Vēlmju Sarakstus'])[1]/following::span[7]</value>
      <webElementGuid>5391888b-b126-4f00-8418-653e82cfc701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valsts'])[1]/preceding::span[3]</value>
      <webElementGuid>d2792554-3b97-4632-b6ef-6492bbb115be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valsts'])[3]/preceding::span[8]</value>
      <webElementGuid>b4e32435-c697-4b84-8d52-773f6c259c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Latviešu']/parent::*</value>
      <webElementGuid>4ad2944a-7457-4823-9331-76ed5307a18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>24ff2a85-6d11-460b-9ff3-e111f7735ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Latviešu' or . = 'Latviešu')]</value>
      <webElementGuid>2aed7f3f-81f4-4598-bb2e-c083f89972c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
